db:
  host: "192.168.3.132"
  port: 5432
  username: "postgres"
  password: "root"
  dbname: "vehicle"
  sslMode: "disable"
  timezone: "Asia/Shanghai"

generate:
  modules:
    -
      name: "系统管理"
      tables:
        - "enterprise"
        - "system_user"
        - "department"
    -
      name: "位置管理"
      tables:
        - "vehicle_location_last"
        - "vehicle_location_his"
